### ISSUE TITLE
Enhancement: QueryResult doesn't return tags

### ISSUE THREAD

**Issue by cory-p-oncota** [paulgoldbaum/scala-influxdb-client#1]
Would be great to return the "tags" property as well. Currently I can't support a query with a GROUP BY clause since I can't access the grouped tuples. Would be glad to take this on and submit a PR if you'd like contributors on this repo.

**Comment by paulgoldbaum** [comment]
Hey @cory-p-oncota, by all means, hack away! I haven't documented anything on code structure, compiling or testing, but hopefully it's not too complicated. In any case, feel free to ask anything. Thanks for your time!
