### ISSUE TITLE
Precision not working

### ISSUE THREAD

**Issue by goyalr41** [paulgoldbaum/scala-influxdb-client#11]
Precision variable while querying data is not working and I guess the reason for that is: 

```
params + ("precision" -> precision.toString)
```

buildQueryParameters is making map for (precision -> precision.toString) but influxdb expects parameter to be "epoch" and not "precision". So, shouldn't this be ("epoch" -> precision.toString)?

https://docs.influxdata.com/influxdb/v0.10/guides/querying_data/

**Comment by paulgoldbaum** [comment]
0.4.4 is out with a fix for this.

Thanks for the report!
