### ISSUE TITLE
Support for async-http-client 2.0.0/Netty 4

### ISSUE THREAD

**Issue by andrioni** [paulgoldbaum/scala-influxdb-client#16]
In order to use `scala-influxdb-client` on a project I'm working on, I had to bump async-http-client to the new 2.0.0-RC15 (which uses Netty 4 and has some minor API changes). Would you be interested in a PR with these changes?

**Comment by paulgoldbaum** [comment]
@andrioni today I updated to the latest version in the 1.9 branch but I assume this isn't enough for what you are doing? The 2.0 final milestone seems to be close so if you want you send me the PR now and we'll have it here until they release it.

Thanks for your time!

**Comment by andrioni** [comment]
Unfortunately not, since the 1.9 branch still uses Netty 3.10. But thanks! I'll clean up the code and send a PR as soon I can.
