### ISSUE TITLE
Supporting other TSDBs

### ISSUE THREAD

**Issue by ariens** [paulgoldbaum/scala-influxdb-client#18]
I'm working on a new project that requires a TSDB and was happily writing to InfluxDB (v0.11) with this excellent client.   Scalability is an important requirement for me though and I've since switched to OpenTSDB now that InfluxDB will no longer include clustering support in their open source releases.

It would be great if this project could support OpenTSDB as well.  The HTTP APIs are very similar (at least for writing) and the Database/use of AsyncHttpClient used in this project is very well implemented.  The only real difference I've gleaned so far is that InfluxDB supports multiple fields where each metric in OpenTSDB is a single named value, however both support tags (arbitrary key/value pairs).

Would anyone be open for a discussion?

**Comment by radusw** [comment]
Why don't you go with http://druid.io/ ? I think it's the best alternative

**Comment by paulgoldbaum** [comment]
@ariens First of all, thanks for the kind words :) 

I think that building a library that supports multiple TSDBs could be a good idea. Personally, I would build it on top of driver libraries, one for each TSDB, so this library would only be responsible for abstracting away the differences. In this scenario, scala-influxdb-client would be the driver for influx and would not take on more than one responsibility.

**Comment by ariens** [comment]
Thanks, @radusw that wasn't on my radar...  I've moved towards OpenTSDB mainly because I'm part of the big data platform team at BlackBerry, where I can take advantage of our existing large hadoop clusters.  Running HBase on YARN via slider for OpenTSDB I'm using existing resources for compute and storage.

@paulgoldbaum I'd agree that driver libraries implementing an interface would be ideal.  I'm going to start work on the OpenTSDB library, and then re-evaluate.  I'll reach out afterwards if I feel I have anything of value to offer.

Cheers

**Comment by paulgoldbaum** [comment]
@ariens great, let me know how it goes!
