### ISSUE TITLE
Allow configuring the execution context

### ISSUE THREAD

**Issue by rklaehn** [paulgoldbaum/scala-influxdb-client#19]
There are two places where ExecutionContext.global is hardcoded in the code base. It is used just for some minor result transforms, but nevertheless this can (and does!) cause trouble. It would be good if the ec would be configurable (e.g. just passed as a parameter during construction)

e.g.
https://github.com/paulgoldbaum/scala-influxdb-client/blob/1675f2723da6c09cde749149de0cfe082ba4f3cb/src/main/scala/com/paulgoldbaum/influxdbclient/InfluxDB.scala#L27

**Comment by maciejbak85** [comment]
+1

**Comment by PiotrKlimek** [comment]
+1

**Comment by paulgoldbaum** [comment]
This has been fixed in 0.5.0.

Thanks for the report
