### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by da-liii** [paulgoldbaum/scala-influxdb-client#21]
There are encoding problems when tagv or fieldv are CJK characters.

**Comment by paulgoldbaum** [comment]
Hey @sadhen, thanks a lot for reporting this and for taking the time to do the PR yourself!

Just a question: before aplying the patch, what happens when you use CJK characters? Does it return an error, store garbage in influx, ...?

Thanks!

**Comment by da-liii** [comment]
store garbage in influx but write the bulks or point successfully

**Comment by paulgoldbaum** [comment]
I've just released 0.5.1 with your changes, should be available in a couple of minutes.

Thank you!
