### ISSUE TITLE
InfluxDB class should inherit Closeable interface.

### ISSUE THREAD

**Issue by blmarket** [paulgoldbaum/scala-influxdb-client#25]
As it's strongly suggested to use `close()` after its use.
by providing `Closeable` interface, we can use it try-with-resources statement.

**Comment by paulgoldbaum** [comment]
@blmarket does Scala have that construct? I've only seen it in Java, might have missed it though.

**Comment by blmarket** [comment]
But at least we can assume your classes can be used in Java code?
Just for scala, AFAIK there's no default construct. I thought scala-arm requires resource to have Closeable interface, but actually it doesn't. But even without these mandates, Some classes in well-known library are using `Closeable` interface.

* http://slick.lightbend.com/doc/2.1.0/api/index.html#scala.slick.util.CloseableIterator

**Comment by paulgoldbaum** [comment]
Added in abc916e. Thanks for the feedback!
