### ISSUE TITLE
AsyncHttpClient conflicts with other Netty based libraries

### ISSUE THREAD

**Issue by csaltos** [paulgoldbaum/scala-influxdb-client#28]
First of all, thanks for this library is very useful.

I've tried to use scala-influxdb-client and expose services with Finagle (an RPC system form Twitter) which also uses Netty but a different version of Netty and a dependency versions conflict arises at run time.

The error is:

`java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;`

For solving this error you can include async-http-client as an explicit dependency excluding netty with something like:

`libraryDependencies += "com.paulgoldbaum" %% "scala-influxdb-client" % "0.5.2"`

`libraryDependencies += "org.asynchttpclient" % "async-http-client" % "2.0.32" exclude("org.jboss.netty","netty") exclude("io.netty","netty")`

Please pay attention to the versions you use when including aync-http-client explicitly, obviously this will change with time.

Possible further solutions to this issue may include:

* Shade async-http-client like Play here -> https://github.com/playframework/play-ws#shading
* Try to coordinate with async-http-client and the Netty creators better paths for upgrading
* Do nothing and let the versions get stable with time

**Comment by rpt** [comment]
@csaltos I had the same problem with `grpc-java`. Using newer version of `asynchttpclient` fixes the problem. I will make a pull request with `asynchttpclient:2.1.0-alpha21` which works for me.

**Comment by paulgoldbaum** [comment]
Fixed this by updating to the current release, which is the same in both projects. I'm not sure of the best long-term solution because shading seems like overkill but it might be the only way to avoid these issues. Will think about it.

Thanks for the input!
