### ISSUE TITLE
Improve handling of empty aggregation sets

### ISSUE THREAD

**Issue by cory-p-oncota** [paulgoldbaum/scala-influxdb-client#3]
By default, InfluxDB will return null if an aggregation is performed and the grouping set has no values with the ability to default values through the use of the fill() keyword. Currently, a MalformedResponseException is thrown in this scenario. It'd be advantageous to either have a per-query method to handle this or at least throw a more specific exception for this situation since the feature isn't well documented by the Influx team.

**Comment by paulgoldbaum** [comment]
@cory-p-oncota do you have a minimal test case so I can reproduce this faster?

**Comment by paulgoldbaum** [comment]
Ok, managed to reproduce this. Seems like null is a valid value so I'll add support for it. I hope this is enough but I'm open to ideas on better ways to handle it.
