### ISSUE TITLE
Can not connect on HTTPS

### ISSUE THREAD

**Issue by ElPicador** [paulgoldbaum/scala-influxdb-client#5]
The hosted version of InfluxDB (https://customers.influxdb.com/) needs HTTPS.

But all connection in `com.paulgoldbaum.influxdbclient.HttpClient` are in HTTP (method `get` and `post`)

Could you add an option to be able to connect on HTTPS ?

**Comment by paulgoldbaum** [comment]
Definitely, will add this asap. Thanks for the report!

**Comment by ElPicador** [comment]
Oh thanks !

When do you plan to release the 0.3.2 version ?

**Comment by paulgoldbaum** [comment]
I'll try push a release later today, but it might be tomorrow as I'm trying
to fix a couple of issues with the testing environment. Will let you know
in any case

**Comment by paulgoldbaum** [comment]
@ElPicador 0.4.0 should be available for download in a few minutes. Let me know how it goes!

**Comment by ElPicador** [comment]
Works great, thanks!
