### ISSUE TITLE
Can not get result of multiple queries

### ISSUE THREAD

**Issue by ElPicador** [paulgoldbaum/scala-influxdb-client#6]
It's possible to send multiple queries to influx by concatenating them with `;`.
But the method `com.paulgoldbaum.influxdbclient.InfluxDB.query` returns only the first serie returned by the API.

The issue seems that the method `com.paulgoldbaum.influxdbclient.QueryResult.fromJson` is assuming that the `results` array as only one result [see](https://github.com/paulgoldbaum/scala-influxdb-client/blob/master/src/main/scala/com/paulgoldbaum/influxdbclient/QueryResult.scala#L30).

I'm not sure how you want to tackle this issue, so I'm not doing a PR.

My idea is to add a method to the class `InfluxDB`: `query(query: Seq[String]): Future[QueryResult]` or maybe `query(query: Seq[String]): Future[Seq[QueryResult]]`

What do you think of it?

**Comment by paulgoldbaum** [comment]
Yes, I know of this limitation. I think QueryResult is already somewhat confusing as it is and I didn't want to make it worse if people don't need that functionality.

That said, returning a Seq of QueryResults sounds like a clean way to approach this, so if you want to take a shot at it you are more than welcome :)

**Comment by paulgoldbaum** [comment]
Fixed in 9be252bebd6cf5c2e995174942dc489d8dd0f70d
