### ISSUE TITLE
Point.key also needs to be escaped

### ISSUE THREAD

**Issue by m01** [paulgoldbaum/scala-influxdb-client#9]
It looks like `Point`'s `key` is not passed through `escapeString` before it's passed to InfluxDB. This means that you get HTTP Error 400's like this:

> unable to parse 'some long key (hello),someTag=Hello\ World Some\ Short(value)=78i 1449741968000': invalid field format

Note the absence of `\` before the spaces in the key.

**Comment by paulgoldbaum** [comment]
You're right, fixing this now. Thanks for the report

**Comment by m01** [comment]
Cool, thank you very much for fixing this!
